<?php

/**
 * @file
 * Contains daemons.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function daemons_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the daemons module.
    case 'help.page.daemons':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Daemons') . '</p>';
      return $output;

    default:
  }
}
